#!/bin/bash
echo "Content-Type:text/html;charset=utf-8"
echo "" 
#echo "<script>window.setInterval(function(){
#	window.location.reload();
#},1000);</script>"
echo "<meta http-equiv="refresh" content="5">"
echo '<div style="padding-left:10px;">'
ip="192.168.x.x"
echo '<h5 style="color:#848484;">'
dd=`date`
echo "统计时间: $dd [每5秒刷新1次] 【当前机器ip: $ip】"
echo '</h5>'
echo "<br>"
echo '<h2 style="color:red;margin:-10px 0px;border-left:4px solid;padding:4px;">用户连接情况</h2>'
echo '<pre style="border-left: 4px solid rgb(12, 40, 245);padding:5px;color:#fff;">'
sshpass -p 'passwd' ssh root@$ip -o StrictHostKeyChecking=no 'who'
echo "</pre>"
echo "<br>"
echo "<br>"
echo "<br>"
echo '<h2 style="color:red;margin:-10px 0px;border-left:4px solid;padding:4px;">用户登录失败记录<font style="font-size:12px;">  [ 空记录表示没有用户登录失败记录]</font></h2>'
echo '<pre style="border-left: 4px solid rgb(12, 40, 245);padding:5px;color:#fff;">'
sshpass -p 'passwd' ssh root@$ip -o StrictHostKeyChecking=no 'lastb'
echo "</pre>"
echo "</div>"

