#!/bin/bash
echo "Content-Type:text/html;charset=utf-8"
echo "" 

# 自动刷新当前页面
#echo "<script>window.setInterval(function(){
#	window.location.reload();
#},1000);</script>"
#echo "<meta http-equiv="refresh" content="60">"

# css样式
echo '<style>
body{color:#cecece;}
.title{color: #FF9800;border-left: 4px solid;padding: 4px;}
pre{font-size:14px;border-left: 4px solid #4CAF50;padding: 5px;}
</style>'

# 定义变量
ip="192.168.x.x"
dd=`date`

echo '<div style="padding-left:10px;">'

# 标题
echo '<h1 class="title">硬盘使用情况</h1>'

# 内容
echo '<h5 style="color:#848484;">'
echo "统计时间: $dd 【当前机器ip: $ip】"
echo '</h5>'

# 命令返回结果
echo '<pre>'
sshpass -p "password" ssh root@$ip -o StrictHostKeyChecking=no  'df -hT'
echo '</pre>'

echo '</div>'
